### ISSUE TITLE
Complex scenario

### ISSUE THREAD

**Issue by hadim** [docker/fig#852]
Hi

I am thinking about using fig which seems a really nice tool but my build is pretty complex and I would like to know what do you think about it.

I have three Dockerfile: database (db), application (app) and data.

Before to start my app I first need to init the data container:

1. run data container
2. call init script from db (which will populate data)
3. call start script from db
4. call init script from app (which will populate data through db)

Once these steps are done, data is initialized and I won't need to re run these steps only if I want to start from scratch.

The next step is to start the app:

1. run data container (or recreate it with a backup archive)
2. call start script from db
3. call start script from app

I also have small backup script which consist in archiving and compressing /data in data.

So I guess here I need to use two fig files (or three if I add the backup script) but I don't know how to handle the fact that data container from init step need to be kept for the start step.

I am currently using a Makefile to handle this but it's messy and I really would like to use a tool like fig. My application is here : https://github.com/hadim/docker-omero, if you want to have a look.

Hope I am clear enough and apologize in advance if this thread is not exactly an "issue" but I didn't find any mailing list.

Thanks you

**Comment by hadim** [comment]
Finally, I figured out how to correctly use Fig. However I still have some questions.

Before using Fig I used two scripts to backup and restore a data container from/to an archive files (see https://github.com/hadim/docker-omero/blob/master/backup.sh for example). It's hard to adapt to Fig since Fig uses different container names. How do you suggest me to do that ?

**Comment by hadim** [comment]
I found many of my concerns in various issues. I close here. Sorry for the noise.

**Comment by dnephin** [comment]
This is a common problem, especially when using frameworks like django and rails where the database schemas and fixtures exist as code.

I have been meaning to a couple patterns you can use to solve this problem, but I haven't had a chance yet.  

The short version is:

1. I would do all of the setup/initialize as part of build, not run
2. If your database schemas and fixtures exist as code (because they are exported from a model), then you have two options:
  1. a build system that allows you to export the models to something that can be loaded directly by the database (mysqldump, pg_dump, etc). The disadvantage here is that it requires you to run a script every time a model changes, or you want to add something.
  2. have your database image include all the code for your application (ex: https://github.com/dnephin/readthedocs.org/blob/fig-demo/dockerfiles/database/Dockerfile), using something like https://github.com/6si/shipwright to replace `fig build` will make this easier. This is usually the approach I take

**Comment by hadim** [comment]
Thank you for this clear answer !
