### ISSUE TITLE
Windows Support for Fig

### ISSUE THREAD

**Issue by jeqo** [docker/fig#906]
Hi, 

I'd like to know if there are some plans for support Fig on Windows (as Docker: https://ahmetalpbalkan.com/blog/compiling-docker-cli-on-windows/).

I've installed fig with python and pip, but I get problems with these libraries:
- termios
- fcntl
And I don't know if there are more.

Thanks in advance.

Best,
Jorge

**Comment by dduportal** [comment]
Hi !

There is some existing issues discussing of that you should look at, maybe it'll help you :
* https://github.com/docker/fig/issues/599
* https://github.com/docker/fig/issues/598
* https://github.com/docker/fig/issues/169

I suppose that the docker team have some hard thinkings about that since it should involve boot2docker in the process also, given that fig will be rebranded as docker-compose, without moving to a go-rewritten (Go is statically compiled, and can be used inside Windows as standalone).

On my side, i provide a basic image running fig inside, but it need some complicated volumes mounts and is long away to be perfect (see https://github.com/dduportal/dockerfiles/issues/4 )

**Comment by jeqo** [comment]
Yes, I hope this year we could have Docker and Fig running on Windows natively instead of running over boot2docker. In the mean time I prefer to create a Ubuntu VM on VirtualBox with Vagrant and installing Docker and Fig with Chef. 

Thanks!
Jorge

**Comment by anchapin** [comment]
Jeqo, can you share the vagrantfile that you used for the Ubuntu VM on VirtualBox with Vagrant and docker and fig installed with Chef? I would like to use this setup as well until native support for windows is available. Thanks

**Comment by jeqo** [comment]
Hi, I dont have the Vagrant file now, but I used Vagrant Omnibus plugin to install Chef client in the container: https://github.com/chef/vagrant-omnibus

Hope this helps,
Regards.

**Comment by anchapin** [comment]
Thanks for mentioning that. I haven't tried using Chef with Vagrant yet, and this seems to make that easier. I will try to figure it out from here, but feel free to share any other advice that you have since I am a beginner in Vagrant, Docker, Fig, and Chef. Thanks again.

**Comment by jeqo** [comment]
Actually I created a repo about Vagrant/Chef/Docker configuration: https://github.com/jeqo/docker-vm
Take a look. 

Also I was testing this Chef's "Knife Container" to use chef to create a container: https://docs.chef.io/containers.html

I have some posts about Vagrant and Chef in my blog: http://jeqo.github.io/blog You can send me your feedback through that channel

Regards,
Jorge.

**Comment by dduportal** [comment]
Just to let you know that there is a PR for boot2docker to run in full 64bits userspace => Maybe a future for having fig inside :) https://github.com/boot2docker/boot2docker/pull/748

**Comment by anchapin** [comment]
Thanks for the additional information!
